var EnstCharData = {

/*"Character":[{ position_y, scale }*/

"characters": {

"Tetora":[{ position_y: "74", scale: "24.5", icon:"Tetora.png", group: "group1-A", drive_url: "https://drive.google.com/file/d/17RUgrKXCkNiArsRW8KpddQxA44h9VtPZ/view?usp=sharing"}],
"Hajime":[{ position_y: "84", scale: "23.5", icon:"Hajime.png", group: "group1-A", drive_url: "https://drive.google.com/file/d/1Wrg4LJOYJIl8aXwP05r2vYND6bbHlwiI/view?usp=sharing"}],
"Tomoya":[{ position_y: "72", scale: "23.5", icon:"Tomoya.png", group: "group1-A", drive_url: "https://drive.google.com/file/d/1WThPWoR8m5MDMcZVFNNWNowzV2lC7UE6/view?usp=sharing"}],
"Hinata":[{ position_y: "64", scale: "23.5", icon:"Hinata.png", group: "group1-A", drive_url: "https://drive.google.com/file/d/1V2HqMMGB8j0yoElKCXIYfusD98jUt68G/view?usp=sharing"}],
"Midori":[{ position_y: "25", scale: "25.5", icon:"Midori.png", group: "group1-A", drive_url: "https://drive.google.com/file/d/1My8htkP2cpSF5ICcYyLH-tmYtF_ceGZu/view?usp=sharing"}],
"Tori":[{ position_y: "112", scale: "22.5", icon:"Tori.png", group: "group1-B", drive_url: "https://drive.google.com/file/d/1I8n5DBqNKliqpEDW58LoKsfp1XeRueta/view?usp=sharing"}],
"Shinobu":[{ position_y: "109", scale: "23", icon:"Shinobu.png", group: "group1-B", drive_url: "https://drive.google.com/file/d/1JOEsdxL-wBw1fXTcXzx8jIp-CcS7pOq3/view?usp=sharing"}],
"Yuta":[{ position_y: "64", scale: "23.5", icon:"Yuta.png", group: "group1-B", drive_url: "https://drive.google.com/file/d/1osrJLgLBDfgTofSSMuBwp5OTF5f59cx8/view?usp=sharing"}],
"Mitsuru":[{ position_y: "76", scale: "24", icon:"Mitsuru.png", group: "group1-B", drive_url: "https://drive.google.com/file/d/1OdeC5RwTivQRJRzD9W171o49mAioN63r/view?usp=sharing"}],
"Tsukasa":[{ position_y: "78", scale: "24.5", icon:"Tsukasa.png", group: "group1-B", drive_url: "https://drive.google.com/file/d/14lgpVBTimihmKrgpkOB9osLEdzdRsi2S/view?usp=sharing"}],
"Sora":[{ position_y: "99", scale: "23", icon:"Sora.png", group: "group1-B", drive_url: "https://drive.google.com/file/d/1TaWLh3J6AY0BAvANnDbmf3xSOTyM3L5C/view?usp=sharing"}],
"Subaru":[{ position_y: "62", scale: "24", icon:"Subaru.png", group: "group2-A", drive_url: "https://drive.google.com/file/d/1iCIWwvMNf-khkOiCP6RpHjgnbb2ovCit/view?usp=sharing"}],
"Hokuto":[{ position_y: "53", scale: "24.5", icon:"Hokuto.png", group: "group2-A", drive_url: "https://drive.google.com/file/d/15wmBbSpEHpRj0YmEmfMBXoC7TbMTQCWd/view?usp=sharing"}],
"Makoto":[{ position_y: "47", scale: "24.5", icon:"Makoto.png", group: "group2-A", drive_url: "https://drive.google.com/file/d/1Tcfucw9XsmlFrRchSjySqhMOCqPFh8Bd/view?usp=sharing"}],
"Souma":[{ position_y: "47", scale: "24.5", icon:"Souma.png", group: "group2-A", drive_url: "https://drive.google.com/file/d/1Dr02GZRYkCgEudZxgJV33CJUI-SVAOXt/view?usp=sharing"}],
"Adonis":[{ position_y: "28", scale: "25.5", icon:"Adonis.png", group: "group2-A", drive_url: "https://drive.google.com/file/d/1JEesQvSXYuV8-jwyF1TroHUdsdCxsRyq/view?usp=sharing"}],
"Natsume":[{ position_y: "71", scale: "24", icon:"Natsume.png", group: "group2-A", drive_url: "https://drive.google.com/file/d/1vQlsiK_cMzkszPh2H_K63_-q-m4FuxO4/view?usp=sharing"}],
"Koga":[{ position_y: "48", scale: "25.3", icon:"Koga.png", group: "group2-B", drive_url: "https://drive.google.com/file/d/1jh7g55S_YXCismXL15C73XTsdjReJXWT/view?usp=sharing"}],
"Ritsu":[{ position_y: "64", scale: "24.5", icon:"Ritsu.png", group: "group2-B", drive_url: "https://drive.google.com/file/d/1gg-VHpFi4usA0L9AABvPBXMkgl8GnKIa/view?usp=sharing"}],
"Mao":[{ position_y: "70", scale: "24.6", icon:"Mao.png", group: "group2-B", drive_url: "https://drive.google.com/file/d/1OGV_HJCgM7CjOdtX7CAtnJPuXEaWlWiC/view?usp=sharing"}],
"Yuzuru":[{ position_y: "43", scale: "25.5", icon:"Yuzuru.png", group: "group2-B", drive_url: "https://drive.google.com/file/d/1pC9XpeUkwwDq90MskisLr-7-dcC_d4rx/view?usp=sharing"}],
"Arashi":[{ position_y: "40", scale: "25.3", icon:"Arashi.png", group: "group2-B", drive_url: "https://drive.google.com/file/d/1pC9XpeUkwwDq90MskisLr-7-dcC_d4rx/view?usp=sharing"}],
"Mika":[{ position_y: "60", scale: "24.5", icon:"Mika.png", group: "group2-B", drive_url: "https://drive.google.com/file/d/1H6TOhcc02HG04DN4sgN_adUw7OSHN5S6/view?usp=sharing"}],
"Keito":[{ position_y: "24", scale: "25.3", icon:"Keito.png", group: "group3-A", drive_url: "https://drive.google.com/file/d/124Mt8CSEvLdyA3to2nDBWApKUMUl6NKj/view?usp=sharing"}],
"Eichi":[{ position_y: "19", scale: "25", icon:"Eichi.png", group: "group3-A", drive_url: ""}],
"Kaoru":[{ position_y: "22", scale: "25.3", icon:"Kaoru.png", group: "group3-A", drive_url: ""}],
"Izumi":[{ position_y: "55", scale: "25.2", icon:"Izumi.png", group: "group3-A", drive_url: ""}],
"Chiaki":[{ position_y: "44", scale: "25.5", icon:"Chiaki.png", group: "group3-A", drive_url: "https://drive.google.com/file/d/1popkdGQFXr4lYTPh1PoKoF-abXpKPx0h/view?usp=sharing"}],
"Shu":[{ position_y: "33", scale: "25", icon:"Shu.png", group: "group3-A", drive_url: "https://drive.google.com/file/d/1pn1LEGFq_pBOPQLRq3dgIGUOBgquSyoi/view?usp=sharing"}],
"Madara":[{ position_y: "15", scale: "25.5", icon:"Madara.png", group: "group3-A", drive_url: "https://drive.google.com/file/d/1xPGHQXDomz4AJU_5-R4trLSN5XVoWKHp/view?usp=sharing"}],
"Kuro":[{ position_y: "18", scale: "25.5", icon:"Kuro.png", group: "group3-B", drive_url: "https://drive.google.com/file/d/1s2acNAfJALGqG2tBUfErK83aQ5Apirtg/view?usp=sharing"}],
"Wataru":[{ position_y: "14", scale: "24.5", icon:"Wataru.png", group: "group3-B", drive_url: "https://drive.google.com/file/d/1nnDZMV7UmkL5wPVs4-CzC2DlOAj2f1Q5/view?usp=sharing"}],
"Kanata":[{ position_y: "32", scale: "25.2", icon:"Kanata.png", group: "group3-B", drive_url: "https://drive.google.com/file/d/1_-3uC1ARLnHDiTbt2QbLJnAztOVPO0IP/view?usp=sharing"}],
"Rei":[{ position_y: "19", scale: "25", icon:"Rei.png", group: "group3-B", drive_url: "https://drive.google.com/file/d/1ealjbG_fZmTGystnluKU8Mseq1nSgO0m/view?usp=sharing"}],
"Nazuna":[{ position_y: "105", scale: "24.2", icon:"Nazuna.png", group: "group3-B", drive_url: "https://drive.google.com/file/d/1Ck52BJ25B1rlRrSYCSpFM4GffwtnRTuX/view?usp=sharing"}],
"Leo":[{ position_y: "75", scale: "24.8", icon:"Leo.png", group: "group3-B", drive_url: "https://drive.google.com/file/d/1zXsUVHyqqc5v0hJ8Yd2LCIrUqqD6zcgU/view?usp=sharing"}],
"Tsumugi":[{ position_y: "33", scale: "25.5", icon:"Tsumugi.png", group: "group3-B", drive_url: "https://drive.google.com/file/d/1nnDZMV7UmkL5wPVs4-CzC2DlOAj2f1Q5/view?usp=sharing"}],
"Nagisa":[{ position_y: "29", scale: "25.5", icon:"Nagisa.png", group: "groupEden", drive_url: ""}],
"Hiyori":[{ position_y: "34", scale: "25.5", icon:"Hiyori.png", group: "groupEden", drive_url: ""}],
"Ibara":[{ position_y: "50", scale: "25.2", icon:"Ibara.png", group: "groupEden", drive_url: "https://drive.google.com/file/d/1Voa08ZcsIHyNn305mmixU_EnU7FapywX/view?usp=sharing"}],
"Jun":[{ position_y: "54", scale: "25.2", icon:"Jun.png", group: "groupEden", drive_url: ""}],
"Jin":[{ position_y: "38", scale: "25.5", icon:"Jin.png", group: "groupTeachers", drive_url: ""}],
"Akiomi":[{ position_y: "36", scale: "25.5", icon:"Akiomi.png", group: "groupTeachers", drive_url: ""}],
"Seiya":[{ position_y: "25", scale: "25.3", icon:"Seiya.png", group: "groupTeachers", drive_url: ""}]
}
}