'use strict';var Ty={TAB:0,al:1,yp:2},Uy=function(){return new qb("MediaRouter.CastStreaming.Session.Launch")},Vy=function(){return new wb("MediaRouter.CastStreaming.Session.Length")},Wy=function(a){Ab("MediaRouter.CastStreaming.Start.Success",a,Ty)};var Xy=fb("mr.mirror.cast.LogUploader"),Zy=function(a,b,c){Yy("raw_events.log.gz",a,b,c);return b?"https://crash.corp.google.com/samples?reportid=&q="+encodeURIComponent("UserComments='"+b+"'"):""},Yy=function(a,b,c,d){if(0==b.size)B(Xy,"Trying to upload an empty file to Crash"),d&&d(null);else{var e=new FormData;e.append("prod","Cast");e.append("ver",chrome.runtime.getManifest().version);e.append(a,b);c&&e.append("comments",c);ww("https://clients2.google.com/cr/report",function(f){f=f.target;var g=
null;Gw(f)?(g=Iw(f),B(Xy,"Upload to Crash succeeded: "+g)):B(Xy,"Upload to Crash failed. HTTP status: "+f.Qa());d&&d(g)},"POST",e,void 0,3E4)}};var $y=function(){this.g=0;hm(this)},bz=function(){az||(az=new $y);return az},cz=function(){var a=bz(),b={fraction:.01,autoSubmitTimeLimitMillis:6048E5},c=b.autoSubmitTimeLimitMillis,d=Date.now();return a.g&&c&&d-a.g<c?!1:Math.random()<b.fraction};$y.prototype.Na=function(){return"mirror.cast.LogUtils"};$y.prototype.Bb=function(){return[void 0,{lastAutoSubmitMillis:this.g}]};$y.prototype.Ab=function(){var a=fm(this);this.g=a&&a.lastAutoSubmitMillis||0};var az=null;fb("mr.mirror.cast.LogUtils");var dz={FD:"OFFER",fw:"ANSWER",tE:"PRESENTATION",cA:"GET_STATUS",gH:"STATUS_RESPONSE",Xz:"GET_CAPABILITIES",Cx:"CAPABILITIES_RESPONSE",jG:"RPC"};var ez=function(){this.capabilities=this.status=this.g=this.error=this.rpc=this.result=this.type=this.h=this.sessionId=null},hz=function(a){try{if("string"!==typeof a)throw SyntaxError("Cannot parse non-string as JSON");var b;fz(JSON.parse(a),function(d){b=gz(d)},function(){throw Error("non-Object result from JSON parse");});return b}catch(d){var c=d instanceof SyntaxError?"JSON parse error: "+d.message:"Type coercion error: "+d.message}"string"==typeof a?a="a string: "+a:a instanceof ArrayBuffer?
(a=new Uint8Array(a),a="an ArrayBuffer whose base64 is "+btoa(String.fromCharCode.apply(null,a))):a="of invalid data type "+typeof a;throw Error(c+". Input was "+a);},gz=function(a){var b=new ez;null!=a.sessionId&&(b.sessionId=String(a.sessionId));iz(a.seqNum,function(f){b.h=f},function(){throw Error('"seqNum" must be a number');});if("type"in a){for(var c=String(a.type).toUpperCase(),d=n(Object.keys(dz)),e=d.next();!e.done;e=d.next())if(dz[e.value]==c){b.type=c;break}if(!b.type)throw Error('not a known message "type"');
}"result"in a&&(b.result=String(a.result));if("rpc"in a){if("string"!==typeof a.rpc)throw Error('"rpc" must be a String containing a base64 payload');b.rpc=new Uint8Array([].concat(q(atob(a.rpc))).map(function(f){return f.charCodeAt(0)}))}fz(a.error,function(f){b.error=jz(f)},function(){throw Error('"error" must be an Object');});fz(a.answer,function(f){b.g=kz(f)},function(){throw Error('"answer" must be an Object');});fz(a.status,function(f){b.status=lz(f)},function(){throw Error('"status" must be an Object');
});fz(a.capabilities,function(f){b.capabilities=mz(f)},function(){throw Error('"capabilities" must be an Object');});return b},fz=function(a,b,c){void 0!==a&&(a instanceof Object?b(a):c())},iz=function(a,b,c){void 0!==a&&("number"!==typeof a?c():b(a))},nz=function(a,b,c){void 0!==a&&(a instanceof Array&&a.every(function(d){return"number"===typeof d})?b(a):c())},oz=function(a,b,c){void 0!==a&&(a instanceof Array?b(a.map(function(d){return String(d)})):c())},pz=function(){this.w=null;this.g=[];this.h=
[];this.j=this.l=this.m=null},kz=function(a){var b=new pz;iz(a.udpPort,function(c){b.w=c},function(){throw Error('"answer.udpPort" must be a number');});nz(a.sendIndexes,function(c){b.g=c},function(){throw Error('"answer.sendIndexes" must be an array of numbers');});nz(a.ssrcs,function(c){b.h=c},function(){throw Error('"answer.ssrcs" must be an array of numbers');});"IV"in a&&(b.m=String(a.IV));"receiverGetStatus"in a&&(b.l="true"==String(a.receiverGetStatus).toLowerCase());"castMode"in a&&(b.j=String(a.castMode));
return b},qz=function(){this.details=this.description=this.code=null},jz=function(a){var b=new qz;iz(a.code,function(c){b.code=c},function(){throw Error('"error.code" must be a number');});"description"in a&&(b.description=String(a.description));fz(a.details,function(c){b.details=c},function(){throw Error('"error.details" must be an Object');});return b},rz=function(){this.h=this.g=null},lz=function(a){var b=new rz;iz(a.wifiSnr,function(c){b.g=c},function(){throw Error('"status.wifiSnr" must be a number');
});nz(a.wifiSpeed,function(c){b.h=c},function(){throw Error('"status.wifiSpeed" must be an array of numbers');});return b},sz=function(){this.h=this.g=null},mz=function(a){var b=new sz;oz(a.mediaCaps,function(c){b.g=c},function(){throw Error('"capabilities.mediaCaps" must be an array');});if("keySystems"in a){a=a.keySystems;if(!(a instanceof Array))throw Error('"capabilities.keySystems" must be an array');b.h=a.map(function(c){var d;fz(c,function(e){d=tz(e)},function(){throw Error('"capabilities.keySystems" entries must be *Objects');
});return d})}return b},uz=function(){this.h=this.m=this.w=this.l=this.u=this.g=this.o=this.codecs=this.initDataTypes=this.j=null},tz=function(a){var b=new uz;"keySystemName"in a&&(b.j=String(a.keySystemName));oz(a.initDataTypes,function(c){b.initDataTypes=c},function(){throw Error('"capabilities.initDataTypes" must be an array');});oz(a.codecs,function(c){b.codecs=c},function(){throw Error('"capabilities.codecs" must be an array');});oz(a.secureCodecs,function(c){b.o=c},function(){throw Error('"capabilities.secureCodecs" must be an array');
});oz(a.audioRobustness,function(c){b.g=c},function(){throw Error('"capabilities.audioRobustness" must be an array');});oz(a.videoRobustness,function(c){b.u=c},function(){throw Error('"capabilities.videoRobustness" must be an array');});"persistentLicenseSessionSupport"in a&&(b.l=String(a.persistentLicenseSessionSupport));"persistentReleaseMessageSessionSupport"in a&&(b.w=String(a.persistentReleaseMessageSessionSupport));"persistentStateSupport"in a&&(b.m=String(a.persistentStateSupport));"distinctiveIdentifierSupport"in
a&&(b.h=String(a.distinctiveIdentifierSupport));return b};var vz=function(a){this.s=fb("mr.mirror.cast.MessageDispatcher");this.l=a;this.g=null;this.h=new Map;this.j=0};vz.prototype.subscribe=function(a,b){if(this.h.has(a))throw Error("Attempt to multiple-subscribe to the same response type: "+a);this.h.set(a,b);this.j=0;mb(this.s,"Added subscriber for "+a+"-type messages.");this.g||(this.g=Px(this.l),this.g.onMessage=this.w.bind(this))};
var wz=function(a,b){a.h.delete(b)&&mb(a.s,function(){return"Removed subscriber of "+b+"-type messages."});0==a.h.size&&a.g&&(a.g.Xa(),a.g=null)};vz.prototype.sendMessage=function(a){return this.g?"RPC"==a.type?this.g.sendMessage(a,{namespace:"urn:x-cast:com.google.cast.remoting"}):this.g.sendMessage(a,{namespace:"urn:x-cast:com.google.cast.webrtc"}):Promise.reject(Error("Require at least one subscriber before sending messages."))};
var xz=function(a,b,c,d,e){var f=null,g=function(){wz(a,c);null!=f&&(clearTimeout(f),f=null)};try{a.subscribe(c,function(h){e(h)&&g()})}catch(h){e(null,h);return}f=setTimeout(function(){g();e(null,Error("timeout"))},d);a.sendMessage(b).catch(function(h){g();e(null,h)})};
vz.prototype.w=function(a){if(a&&"string"===typeof a.namespace_&&a.namespace_.startsWith("urn:x-cast:com.google.cast.")){do{var b=void 0;try{b=hz(a.data)}catch(d){b=d.message;break}if(b.type){var c=this.h.get(b.type);if(c)try{c(b);return}catch(d){b="Error thrown during delivery. Response was: "+(JSON.stringify(b)+". Error from subscriber callback was: ")+(d.message+".")}else b="Message was ignored: "+JSON.stringify(b)}else b="Message did not include response type: "+JSON.stringify(b)}while(0);10>
this.j?this.s.K(b):mb(this.s,b);++this.j}};var yz=function(){this.g=Promise.resolve(1)},Az=function(a,b,c){return zz(a,function(d){return d==b},c)},Bz=function(a,b){var c=[3,4];return zz(a,function(d){return-1!=c.indexOf(d)},b)},Cz=function(a,b){a.g=a.g.catch(function(){return 1});return zz(a,function(){return!0},b)},zz=function(a,b,c){var d,e,f=new Promise(function(g,h){d=g;e=h});a.g=a.g.then(function(g){if(!b(g))return e(Error("Operation requires a different starting checkpoint than "+g)),Promise.resolve(g);var h=new Dz(g);try{var l=c(h)}catch(p){l=
Promise.reject(p)}return l.then(function(p){return d(p)},function(p){return e(p)}).then(function(){if(null===h.g)throw Error("A prior operation that started at "+(g+" did not complete."));return h.g})},function(g){e(g);throw g;});return f},Dz=function(a){this.h=a;this.g=null},Ez=function(a,b){a.g="number"===typeof b?b:a.h};var Fz=chrome.cast.streaming,Gz=fb("mr.mirror.cast.StreamingLaunchWorkflow"),Iz=function(a,b,c,d,e){this.L=a.sessionId;this.D=a.Gf;this.R=a.ee;this.j=b;this.H=c;this.G=d;this.Fa=Hz(e,"onAnswer",this.D);this.W=Hz(e,"onSessionStop",this.D);this.s=Gz;this.C=new yz;this.o=this.F=this.u=this.h=this.g=this.m=this.w=this.l=null};
Iz.prototype.start=function(a,b,c){var d=this;if(!a&&!b)return Promise.reject(Error("No tracks to stream"));var e=a instanceof Jz,f=b instanceof Jz;(e&&b&&!f||f&&a&&!e)&&Jb("Mixing remoting and non-remoting tracks");return Az(this.C,1,function(g){d.l=a;d.w=b;d.m=c;B(d.s,function(){return"Launching streaming for "+Kz(d)+" to a "+(d.R+".")});return Lz(d).then(d.J.bind(d)).then(function(h){return Mz(d,h).then(function(l){d.Fa();var p=Nz(d,l,h);d.g=Oz(d,d.g,p);d.h=Oz(d,d.h,p);if(!d.g&&!d.h)throw Error("Receiver did not select any offers from: "+
JSON.stringify(h));d.F=!!l.l;d.o=function(r,t){r==d.g?d.m.Ee("Audio stream (id="+r+") error: "+t):r==d.h&&d.m.Ee("Video stream (id="+r+") error: "+t)};Fz.rtpStream.onError.addListener(d.o);return Pz(d,l,p)})}).then(function(){B(d.s,function(){return"Launched streaming for "+Kz(d)});d.m.jg(d);Ez(g,2);return{Iq:d.g,Jv:d.h}})})};
Iz.prototype.stop=function(){var a=this;return Cz(this.C,function(b){if(!a.l&&!a.w)return Ez(b,1),Promise.resolve();B(a.s,function(){return"Stopping streaming for "+Kz(a)+"."});a.o&&(Fz.rtpStream.onError.removeListener(a.o),a.o=null);if(a.m){var c=a.m.Yg();a.m=null}else c=Promise.resolve();return c.then(function(){a.g&&(Fz.rtpStream.stop(a.g),Fz.rtpStream.destroy(a.g),a.g=null);a.h&&(Fz.rtpStream.stop(a.h),Fz.rtpStream.destroy(a.h),a.h=null);a.u&&(Fz.udpTransport.destroy(a.u),a.u=null);a.W();B(a.s,
function(){return"Stopped streaming for "+Kz(a)+"."});a.l=null;a.w=null;Ez(b,1)})})};
var Qz=function(a,b){var c=JSON.stringify(b);return Promise.all([a.g&&new Promise(function(d){return Fz.rtpStream.getRawEvents(a.g,c,d)}),a.h&&new Promise(function(d){return Fz.rtpStream.getRawEvents(a.h,c,d)})]).catch(function(d){a.s.error("Unexpected error when calling getRawEvents()",d);return[]}).then(function(d){return new Blob(d.filter(function(e){return!!e}),{type:"application/gzip"})})},Rz=function(a){return Promise.all([a.g&&new Promise(function(b){return Fz.rtpStream.getStats(a.g,b)}),a.h&&
new Promise(function(b){return Fz.rtpStream.getStats(a.h,b)})]).catch(function(b){a.s.error("Unexpected error when calling getStats()",b);return[]}).then(function(b){return Object.assign.apply(Object,[{}].concat(q(b.filter(function(c){return!!c}))))})},Kz=function(a){if(a.l&&a.w)var b="audio+video ";else if(a.l)b="audio-only ";else if(a.w)b="video-only ";else return"stopped";return a.l instanceof Jz||a.w instanceof Jz?b+"remoting":b+"streaming"},Lz=function(a){return new Promise(function(b){var c=
function(d,e,f){d&&!a.l&&(Fz.rtpStream.destroy(d),d=null);e&&!a.w&&(Fz.rtpStream.destroy(e),e=null);B(a.s,function(){return"Created Cast Streaming session: audioStreamId="+d+", videoStreamId="+e+"."});a.g=d;a.h=e;a.u=f;b()};a.l instanceof Jz||a.w instanceof Jz?Fz.session.create(null,null,c):Fz.session.create(a.l,a.w,c)})};
Iz.prototype.J=function(){for(var a=fk(),b=fk(),c=[],d=n([this.g,this.h]),e=d.next();!e.done;e=d.next())if(e=e.value)for(var f=e==this.g,g=f?127:96,h=f?Math.floor(499999*Math.random())+1:Math.floor(499999*Math.random())+500001,l=f?48E3:9E4,p=n(Fz.rtpStream.getSupportedParams(e)),r=p.next();!r.done;r=p.next())r=r.value,r.payload.payloadType=g,r.payload.maxLatency=this.j.maxLatencyMillis,r.payload.minLatency=this.j.minLatencyMillis,r.payload.animatedLatency=this.j.animatedLatencyMillis,r.payload.ssrc=
h,r.payload.clockRate=l,r.payload.aesKey=a,r.payload.aesIvMask=b,f?(r.payload.channels=2,r.payload.maxBitrate=this.j.audioBitrate,r.payload.maxFrameRate=100):(r.payload.minBitrate=this.j.minVideoBitrate,r.payload.maxBitrate=this.j.maxVideoBitrate,r.payload.maxFrameRate=this.j.maxFrameRate),c.push(new Sz(e,r));return c};
var Oz=function(a,b,c){b&&!c.some(function(d){return d.Jf==b})&&(a.s.K("Destroying RTP stream not selected by the receiver: id="+b),Fz.rtpStream.destroy(b),b=null);return b},Mz=function(a,b){return new Promise(function(c,d){for(var e=[],f=0;f<b.length;++f){var g=b[f].params,h={index:f,codecName:g.payload.codecName.toLowerCase(),rtpProfile:"cast",rtpPayloadType:g.payload.payloadType,ssrc:g.payload.ssrc,targetDelay:g.payload.animatedLatency,aesKey:g.payload.aesKey,aesIvMask:g.payload.aesIvMask,timeBase:"1/"+
g.payload.clockRate,receiverRtcpEventLog:a.j.enableLogging,rtpExtensions:["adaptive_playout_delay"]};a.j.dscpEnabled&&(h.receiverRtcpDscp=46);127==g.payload.payloadType?Object.assign(h,{type:"audio_source",bitRate:0<g.payload.maxBitrate?1E3*g.payload.maxBitrate:60*g.payload.maxFrameRate+g.payload.clockRate*g.payload.channels,sampleRate:g.payload.clockRate,channels:g.payload.channels}):Object.assign(h,{type:"video_source",renderMode:"video",maxFrameRate:Math.round(1E3*g.payload.maxFrameRate)+"/1000",
maxBitRate:1E3*g.payload.maxBitrate,resolutions:[{width:a.j.maxWidth,height:a.j.maxHeight}]});e.push(h)}var l=a.l instanceof Jz||a.w instanceof Jz?"remoting":"mirroring",p={type:"OFFER",sessionId:a.L,seqNum:sn(a.H),offer:{castMode:l,receiverGetStatus:!0,supportedStreams:e}};B(a.s,function(){return"Sending OFFER message: "+JSON.stringify(p)});xz(a.G,p,"ANSWER",1E4,function(r,t){if(null==r)d(t);else if("ok"==r.result&&r.g){if(r.h!=p.seqNum)return a.s.K("Ignoring ANSWER for OFFER with different seqNum: "+
JSON.stringify(r)),!1;((t=r.g.j)&&t!=l||!t&&"mirroring"!=l)&&a.s.error("Expected receiver to ANSWER with castMode="+l+", but got: "+t);mb(a.s,function(){return"Received ANSWER: "+JSON.stringify(r)});c(r.g)}else d(Error("Non-OK ANSWER received: "+JSON.stringify(r)));return!0})})},Nz=function(a,b,c){if(b.g.length!=b.h.length)return a.s.error("sendIndexes.length != ssrcs.length in ANSWER: "+JSON.stringify(b)),[];for(var d=[],e={},f=0;f<b.g.length;e={bf:e.bf},++f){var g=b.g[f];if(0>g||g>=c.length)return a.s.error("Receiver selected invalid index ("+
g+" < "+c.length+") in ANSWER: "+JSON.stringify(b)),[];e.bf=c[g];if(d.some(function(h){return function(l){return l.Jf==h.bf.Jf}}(e)))return a.s.error("Receiver selected same RTP stream twice in ANSWER: "+JSON.stringify(b)),[];e.bf.params.payload.feedbackSsrc=b.h[g];if(d.some(function(h){return function(l){return l.params.payload.feedbackSsrc==h.bf.params.payload.feedbackSsrc}}(e)))return a.s.error("Receiver provided same SSRC for two different RTP streams in ANSWER: "+JSON.stringify(b)),[];d.push(e.bf)}return d},
Pz=function(a,b,c){var d=null,e=function(){d&&(Fz.rtpStream.onStarted.removeListener(d),d=null)};return(new Promise(function(f,g){var h=b.w||2344;B(a.s,function(){return"Starting RTP streams to receiver at "+(a.D+":"+h)+(" for selected offers: "+JSON.stringify(c))});var l=a.u||-1;a.j.dscpEnabled&&(B(a.s,"Enabled DSCP in sender."),Fz.udpTransport.setOptions(l,{DSCP:!0}));Fz.udpTransport.setDestination(l,{address:a.D,port:h});var p=new Set(c.map(function(t){return t.Jf}));d=function(t){p.delete(t);
0==p.size&&f()};Fz.rtpStream.onStarted.addListener(d);l=n(c);for(var r=l.next();!r.done;r=l.next())r=r.value,Fz.rtpStream.toggleLogging(r.Jf,a.j.enableLogging),Fz.rtpStream.start(r.Jf,r.params);setTimeout(function(){g(Error("Timeout: RTP streams failed to start."))},1E4)})).then(e).catch(function(f){e();throw f;})},Hz=function(a,b,c){return a&&b in a?function(){try{a[b](c)}catch(d){Gz.error("Error from testHooks."+b,d)}}:function(){}},Sz=function(a,b){this.Jf=a;this.params=b},Jz=function(){};var Tz=fb("mr.mirror.cast.MediaRemoter"),Wz=function(a,b,c,d,e,f){this.o=a;this.G=Uz(b,this.o.sb);this.H=new Iz(this.o.sb,c,d,e,f);this.F=e;this.w=new yz;this.j=new Vz;this.C=new mojo.Binding(mojo.MirrorServiceRemoter,this,null);this.s=Tz;this.D=this.g=this.m=this.l=this.J=null;this.h=!0;this.u=this.L.bind(this)},Zz=function(a,b,c){return Az(a.w,1,function(d){a.J=b;a.l=c;var e=a.C.createInterfacePtrAndBind();a.C.setConnectionErrorHandler(function(){B(a.s,"Remoter mojo pipe connection error.");Xz(a)});
a.g=new mojo.MirrorServiceRemotingSourcePtr;var f=wj(a.o.mediaSource||"");if(!f)throw Error("Failed to parse tab ID from source:\n          "+a.o.mediaSource);B(a.s,"Connecting remoter to browser: tabId="+f);(fj.get("mr.ProviderManager")||null).onMediaRemoterCreated(f,e,mojo.makeRequest(a.g));a.g.ptr.setConnectionErrorHandler(function(){B(a.s,"RemotingSource mojo pipe connection error.");Xz(a)});return Yz(a).then(function(){if(a.h)a.g.onSinkAvailable(a.G);Ez(d,2)})})},Xz=function(a){return Cz(a.w,
function(b){a.g&&(a.g.ptr.reset(),a.g=null);var c=a.m;a.m=null;a.l=null;a.J=null;a.C.close();chrome.settingsPrivate.onPrefsChanged.hasListener(a.u)&&chrome.settingsPrivate.onPrefsChanged.removeListener(a.u);return new Promise(function(d){window.setTimeout(function(){$z(a).then(function(){Ez(b,1);d();c&&c()})},250)})})};k=Wz.prototype;k.Tu=function(a){aA(this.j,a)};k.jg=function(a){this.l&&this.l.jg(a)};k.Yg=function(){return this.l?this.l.Yg():Promise.resolve()};
k.Ee=function(a,b){this.s.error("Error during streaming: "+a,b);if(this.g)this.g.onError();Xz(this)};
k.start=function(){var a=this,b=!1;B(this.s,function(){b=!0;return"Starting next media remoting session."});b&&bA(this.j,function(c){return B(a.s,c)});cA(this.j);Az(this.w,2,function(c){return(0,a.J)().then(function(d){a.m=d;a.F.subscribe("RPC",function(e){if(e.rpc){var f=a.j;e=e.rpc;f.m&&(++f.o,f.h+=e.length,f.m(e))}});Ez(c,3)}).catch(function(d){return $z(a).then(function(){Ez(c);throw d;})})}).then(function(){B(a.s,"Remoting started successfully.")}).catch(function(c){a.s.error("Failed to start remoting",
c);a.g.onError()})};k.rv=function(a,b){var c=this;return Az(this.w,3,function(d){return c.H.start(a?new Jz:null,b?new Jz:null,c).then(function(e){dA(c.j,function(f){return c.F.sendMessage(f)},function(f){c.g.onMessageFromSink(f)});Ez(d,4);return{audio_stream_id:e.Iq||-1,video_stream_id:e.Jv||-1}}).catch(function(e){return $z(c).then(function(){Ez(d);throw e;})})}).catch(function(d){c.s.error("Failed to start remoting streams",d);Xz(c);return{audio_stream_id:-1,video_stream_id:-1}})};
k.stop=function(a){var b=this;Bz(this.w,function(c){b.g.onStopped(a);return $z(b).then(function(){B(b.s,"Remoting stopped.");Ez(c,5);(0,b.m)().then(function(){return Az(b.w,5,function(d){if(b.g&&b.h)b.g.onSinkAvailable(b.G);Ez(d,2);return Promise.resolve()})}).catch(function(d){throw d;});b.m=null})}).catch(function(c){b.s.error("Failed to stop remoting: ",c);Xz(b)})};
k.gr=function(){null===this.D&&(this.D=yf(this.o.sb.Gf).then(function(a){return a.h||!1}));return this.D.then(function(a){return{rate:(a?1E7:5E6)/8}})};
var $z=function(a){return a.H.stop().then(function(){wz(a.F,"RPC");eA(a.j);fA(a.j)})},Yz=function(a){return new Promise(function(b){chrome.settingsPrivate.getPref("media_router.media_remoting.enabled",function(c){chrome.runtime.lastError?a.s.error("Encountered error getting media remoting pref: "+JSON.stringify(chrome.runtime.lastError)):c.type!=chrome.settingsPrivate.PrefType.BOOLEAN?a.s.error("Pref value not a boolean: "+JSON.stringify(c)):(a.h=!!c.value,B(a.s,"Initializing mediaRemotingEnabled_ with value read from pref: "+
a.h));chrome.settingsPrivate.onPrefsChanged.hasListener(a.u)||chrome.settingsPrivate.onPrefsChanged.addListener(a.u);b()})})};
Wz.prototype.L=function(a){if(this.g){a=n(a);for(var b=a.next();!b.done;b=a.next())if(b=b.value,"media_router.media_remoting.enabled"==b.key){if(b.type!=chrome.settingsPrivate.PrefType.BOOLEAN){this.s.error("Pref value not a boolean: "+JSON.stringify(b));break}a=!!b.value;if(this.h==a)break;this.h=a;B(this.s,"mediaRemotingEnabled_ changed to: "+this.h);if(this.h)this.g.onSinkAvailable(this.G);else this.g.onStopped(mojo.RemotingStopReason.USER_DISABLED);break}}};
var Uz=function(a,b){var c=new mojo.RemotingSinkMetadata;c.features=[];c.friendly_name=b.nv||"";c.audio_capabilities=[];c.video_capabilities=[];var d=mojo.RemotingSinkAudioCapability,e=mojo.RemotingSinkVideoCapability,f=c.audio_capabilities,g=c.video_capabilities,h=b.ee||"";(a.g||[]).forEach(function(l){switch(l){case "audio":f.push(d.CODEC_BASELINE_SET);break;case "aac":f.push(d.CODEC_AAC);break;case "opus":f.push(d.CODEC_OPUS);break;case "video":g.push(e.CODEC_BASELINE_SET);break;case "4k":g.push(e.SUPPORT_4K);
break;case "h264":g.push(e.CODEC_H264);break;case "vp8":g.push(e.CODEC_VP8);break;case "vp9":h.startsWith("Chromecast Ultra")&&g.push(e.CODEC_VP9);break;case "hevc":h.startsWith("Chromecast Ultra")&&g.push(e.CODEC_HEVC);break;default:B(Tz,"Unknown mediaCap name: "+l)}});b.ee&&"Chromecast Ultra"==b.ee&&g.push(e.SUPPORT_4K);return c};Wz.prototype.estimateTransmissionCapacity=Wz.prototype.gr;Wz.prototype.stop=Wz.prototype.stop;Wz.prototype.startDataStreams=Wz.prototype.rv;Wz.prototype.start=Wz.prototype.start;
Wz.prototype.sendMessageToSink=Wz.prototype.Tu;
var Vz=function(){this.m=this.w=this.g=null;this.D=this.h=this.o=this.j=this.u=0;this.l=null},cA=function(a){a.g=[];gA(a,performance.now())},dA=function(a,b,c){a.w=b;a.m=c;a.g?(b=a.g,a.g=null,b.forEach(function(d){return aA(a,d.data).then(d.Vu,d.Yn)})):gA(a,performance.now())},eA=function(a){if(a.g){var b=Error("Stop before delivering pending message");a.g.forEach(function(c){return c.Yn(b)});a.g=null}a.w=null;a.m=null},aA=function(a,b){if(a.w){var c=btoa(String.fromCharCode.apply(null,b));++a.u;
a.j+=b.length;return a.w({type:"RPC",rpc:c})}return a.g?new Promise(function(d,e){a.g.push({data:b,Vu:d,Yn:e})}):Promise.reject(Error("RPC pipe not started"))},bA=function(a,b){fA(a);a.l=setInterval(function(){if(a.g)var c=a.g.length+" messages are waiting to send.";else{c=performance.now();var d=(c-a.D)/1E3;d="Over the past "+d.toFixed(1)+" seconds, sent "+(a.u+" messages ("+Math.round(a.j/d)+" bytes/sec) and received ")+(a.o+" messages ("+Math.round(a.h/d)+" bytes/sec).");gA(a,c);c=d}b(c)},3E4)},
fA=function(a){null!=a.l&&(clearInterval(a.l),a.l=null)},gA=function(a,b){a.u=0;a.j=0;a.o=0;a.h=0;a.D=b};var hA=function(a){return a&&a.getAudioTracks()&&0<a.getAudioTracks().length?a.getAudioTracks()[0]:null},iA=function(a){return a&&a.getVideoTracks()&&0<a.getVideoTracks().length?a.getVideoTracks()[0]:null};var jA=function(a,b,c,d,e){this.j=new Iz(a,b,c,d,void 0===e?null:e);this.s=fb("mr.mirror.cast.MediaStreamer");this.w=new yz;this.l=this.h=this.g=this.m=null};jA.prototype.start=function(a,b){var c=this;return Az(this.w,1,function(d){c.m=a;c.g=hA(a);c.g&&"ended"==c.g.readyState&&(c.g=null);c.h=iA(a);c.h&&"ended"==c.h.readyState&&(c.h=null);if(!c.g&&!c.h)return Ez(d),Promise.reject(Error("No MediaStream tracks to stream."));c.l=b;return c.j.start(c.g,c.h,c.l).then(function(){return Ez(d,2)})})};
jA.prototype.stop=function(){var a=this;return Cz(this.w,function(b){return a.j.stop().then(function(){a.g=null;a.h=null;a.m=null;a.l=null;Ez(b,1)})})};var kA=function(a){return Az(a.w,2,function(b){B(a.s,"Suspending media streaming...");return a.j.stop().then(function(){B(a.s,"Suspended media streaming.");Ez(b,3)})})};
jA.prototype.resume=function(){var a=this;return Az(this.w,3,function(b){a.g&&"ended"==a.g.readyState&&(a.g=null);a.h&&"ended"==a.h.readyState&&(a.h=null);if(!a.g&&!a.h)return Promise.reject(Error("Cannot resume: All tracks have ended."));B(a.s,"Resuming media streaming...");return a.j.start(a.g,a.h,a.l).then(function(){B(a.s,"Resumed media streaming.");Ez(b,2)})})};var lA=function(a,b,c){this.w=a;this.l=b;this.j=c;this.s=fb("mr.mirror.cast.WifiStatusMonitor");this.g=null;this.h=[]};lA.prototype.start=function(){var a=this;null==this.g&&(mb(this.s,"Starting Wifi Status Monitoring."),this.h=[],this.j.subscribe("STATUS_RESPONSE",function(b){return mA(a,b)}),this.g=setInterval(function(){return nA(a)},12E4),nA(this))};lA.prototype.stop=function(){null!=this.g&&(mb(this.s,"Stopping Wifi Status Monitoring."),clearInterval(this.g),this.g=null,wz(this.j,"STATUS_RESPONSE"))};
var mA=function(a,b){if(null!=a.g)if(b.status){var c={};null!=b.status.g&&(c.wifiSnr=b.status.g);null!=b.status.h&&(c.wifiSpeed=b.status.h[3]);0==Object.keys(c).length?a.s.K(function(){return"No status fields populated in response: "+JSON.stringify(b)}):(c.timestamp=Date.now(),30==a.h.length&&a.h.shift(),a.h.push(c),B(a.s,function(){return"Current Wifi status: "+JSON.stringify(c)}))}else a.s.K(function(){return"Ignoring response without status: "+JSON.stringify(b)})},nA=function(a){a.j.sendMessage({type:"GET_STATUS",
sessionId:a.w,seqNum:sn(a.l),get_status:["wifiSnr","wifiSpeed"]})};var oA=function(a,b,c,d){this.G=b.Gf;this.o={extVersion:chrome.runtime.getManifest().version,extChannel:"public",mirrorSettings:Mj(a),sender:navigator.userAgent||"UNKNOWN",receiverProductName:b.ee};this.J=c;this.F=d;this.l=this.h=this.u=this.m=this.w=this.D=this.j=null;this.g=[]};oA.prototype.jg=function(a){null!=this.h&&clearInterval(this.h);this.j=a;this.D=Date.now();this.h=setInterval(this.C.bind(this,a),9E5)};
oA.prototype.Yg=function(){null!=this.h&&(clearInterval(this.h),this.h=null);if(null!=this.j){var a=this.C(this.j);this.j=null;return a}return Promise.resolve()};oA.prototype.Ee=function(a,b){null==this.w&&(this.w=Date.now(),"function"===typeof a?this.m=a():"string"===typeof a&&(this.m=a),b&&"string"===typeof b.stack&&(this.u=b.stack))};
var qA=function(a,b){return(null==a.j?Promise.resolve():a.C(a.j)).then(function(){var c=b.map(function(d){d=pA(a,d);var e=d.map(function(g){return g.events}).filter(function(g){return null!=g}),f=["["];d.map(function(g){return g.If}).forEach(function(g,h){0<h&&f.push(",");f.push(g)});f.push("]");return{events:new Blob(e,{type:"application/gzip"}),If:new Blob(f,{type:"application/json"})}});a.g=[];return c})};
oA.prototype.C=function(a){var b=this;if(null!=this.l)return this.l;var c=yf(this.G).then(function(d){d={receiverVersion:d.g,receiverConnected:d.l,receiverOnEthernet:d.h,receiverHasUpdatePending:d.j,receiverUptimeSeconds:d.w};Object.assign(d,b.o);var e=Date.now();Object.assign(d,{startTime:b.D,endTime:e,activity:Kz(a),receiverWifiStatus:Array.from(b.F.h)});b.D=e;null!=b.w&&(Object.assign(d,{streamingErrorTime:b.w,streamingErrorMessage:b.m,streamingErrorCause:b.u}),b.w=null,b.m=null,b.u=null);return d});
return(this.l=Promise.all([c.then(function(d){return Qz(a,d)}),c,Rz(a)]).then(function(d){var e=n(d);d=e.next().value;var f=e.next().value;e=e.next().value;b.g.push({events:d,If:new Blob([JSON.stringify(Object.assign({tags:f},e))],{type:"application/json"})});b.g=pA(b,b.J);b.l=null}))||Promise.resolve()};
var pA=function(a,b){b-=2;for(var c=[],d=a.g.length-1;0<=d;--d){b-=a.g[d].If.size+1;if(0>b)break;c.push({events:null,If:a.g[d].If});if(null!=a.g[d].events){var e=a.g[d].events.size;b>=e&&(c[c.length-1].events=a.g[d].events,b-=e)}}return c.reverse()};var rA=fb("mr.NetworkUtils"),sA=function(a,b){if(!Ri)return Promise.reject("TDLS feature not enabled.");B(rA,"setTDLSState_: ip="+a+", state="+b);return new Promise(function(c,d){chrome.networkingPrivate.setWifiTDLSEnabledState(a,b,function(e){chrome.runtime.lastError?(rA.K("Unable to set TDLS state: state = "+b+", error = "+chrome.runtime.lastError.message),d("Unable to set TDLS state to "+b+".")):(B(rA,"TDLS state changed: state = "+b+", status = "+e),c(e))})})};var tA=function(a,b,c,d){d=void 0===d?null:d;Jj.call(this,b);var e=b.sb;this.F=e.sessionId;this.L=e.Gf;this.C=a;this.R=d;this.s=fb("mr.mirror.cast.Session");this.D=new yz;this.u=new rn("mirror.cast.SeqNumGenerator");this.o=new vz(b.id);this.m=new jA(e,this.C,this.u,this.o,this.R);this.w=null;this.g=new oA(a,e,c,new lA(this.F,this.u,this.o));this.l=!1;this.J=null};u(tA,Jj);k=tA.prototype;
k.start=function(a){var b=this;return Az(this.D,1,function(c){var d=Uy();return uA(b).then(function(e){b.l=e;return b.m.start(a,b)}).then(function(){if(b.m.j.F){var e=b.g;e.o.tdlsIsOn=b.l;e.F.start();vA(b)}else b.g.o.tdlsIsOn=b.l;d.end();b.J=Vy();Ez(c,2);return b})})};
k.stop=function(){var a=this;return Cz(this.D,function(b){a.J&&(a.J.end(),a.J=null);a.g.F.stop();return a.m.stop().then(function(){return a.w?Xz(a.w):Promise.resolve()}).then(function(){a.w=null;return a.l?wA(a):Promise.resolve()}).then(function(){a.l=!1;Ez(b,4)})})};
k.Wn=function(){var a=this,b={sessionId:this.F,seqNum:sn(this.u),type:"PRESENTATION",icons:[],title:Hj(this.pc)};B(this.s,"Sending session metadata update to receiver: "+this.F);this.o.sendMessage(b).catch(function(c){a.s.K("Failed to send activity to sink: "+c.message)})};k.jg=function(a){this.g.jg(a)};k.Yg=function(){return this.g.Yg()};k.Ee=function(a,b){this.g.Ee(a,b);this.s.error(a,b);this.stop()};
var xA=function(a,b){return qA(a.g,b)},uA=function(a){B(a.s,"maybeEnableTdls_: useTdls = "+a.C.useTdls);return a.C.useTdls?sA(a.L,!0).then(function(b){if("Connected"==b)return B(a.s,"Successfully enabled TDLS."),!0;a.s.K("Did not enable TDLS: result="+b);return!1}).catch(function(b){a.s.K("Error while calling enableTDLS()",b);return!1}):Promise.resolve(!1)},wA=function(a){return sA(a.L,!1).catch(function(b){return a.s.error("Error while turning TDLS back off",b)})},vA=function(a){yA(a).then(function(b){(b.g||
[]).includes("video")?zA(a,b):a.s.K(function(){return"Receiver incapable of Media Remoting: "+JSON.stringify(b)})}).catch(function(b){a.s.K("None/Invalid capabilites response. Media Remoting disabled.",b)})},yA=function(a){return new Promise(function(b,c){var d={type:"GET_CAPABILITIES",sessionId:a.F,seqNum:sn(a.u)};B(a.s,function(){return"Sending GET_CAPABILITIES message: "+JSON.stringify(d)});xz(a.o,d,"CAPABILITIES_RESPONSE",3E4,function(e,f){if(null==e)return c(f),!0;if("ok"!=e.result||!e.capabilities)return c(Error("Bad response: "+
JSON.stringify(e))),!0;if(e.h!=d.seqNum)return B(a.s,function(){return"Ignoring CAPABILITIES_RESPONSE with different seqNum: "+JSON.stringify(e)}),!1;mb(a.s,function(){return"Received CAPABILITIES_RESPONSE: "+JSON.stringify(e)});b(e.capabilities);return!0})})},zA=function(a,b){Az(a.D,2,function(c){var d=a.h.sb.ee||"<UNKNOWN>";if(!d.startsWith("Chromecast")&&!d.startsWith("Eureka Dongle"))return a.s.K('HACK: Media Remoting disabled because the receiver model--"'+(d+'" according to discovery--is not a Chromecast.')),
Ez(c),Promise.resolve();a.w=new Wz(a.h,b,a.C,a.u,a.o,a.R);return Zz(a.w,a.Fa.bind(a),a).catch(function(e){a.s.error("Media Remoting start failed: "+e.message,e)}).then(function(){return Ez(c)})})};tA.prototype.Fa=function(){var a=this;return Az(this.D,2,function(b){return new Promise(function(c,d){kA(a.m).then(function(){Ez(b,3);a.G=!0;zj(a);c(a.W.bind(a))}).catch(function(e){a.Ee("Failed to suspend MediaStreamer before starting remoting",e);d(e)})})})};
tA.prototype.W=function(){var a=this;return Az(this.D,3,function(b){return new Promise(function(c,d){a.m.resume().then(function(){Ez(b,2);a.G=!1;zj(a);c()}).catch(function(e){a.Ee("Failed resume MediaStreamer after ending remoting mode",e);d(e)})})})};var AA=function(){xj.call(this,"cast_streaming");this.m=this.D=this.G=this.J=this.l=null;this.da=this.H="";this.ja=this.u=!1;this.sa=this.xa.bind(this);this.L=this.R=this.Fa=this.W=this.w=null};u(AA,xj);k=AA.prototype;k.kg=function(a){this.u=a||!1;this.ja=!0};k.getName=function(){return"cast_streaming"};
k.Sj=function(a,b,c,d,e){var f=this;if(!this.u)return xj.prototype.Sj.call(this,a,b,c,d,e);B(this.O,"Start mirroring on route "+a.id);if(!this.ja)return Ki(Error("Not initialized"));var g=new Promise(function(h,l){f.o().then(function(){if(vj(b)&&c.shouldCaptureVideo)return cj(!1).then(function(p){f.da=p})}).then(function(){return e?e(a).g:a}).then(function(p){f.H=b;BA(f,p);var r=f.J.createInterfacePtrAndBind(),t=f.G.createInterfacePtrAndBind(),z=CA(p,c);DA(f,p,b,d);if(!f.l)throw new Oi("Error to get mirroring service host");
f.D=new mojo.MirroringCastMessageChannelPtr;f.W=Uy();f.l.start(z,r,t,mojo.makeRequest(f.D));f.w=new Jj(a,f.j.L.bind(f.j));zj(f.w);EA(f,p,b);f.R=function(){return h(p)};f.L=l}).catch(function(p){f.O.error("Mirroring launch error: "+p);f.Cf(void 0===p.reason?9:p.reason);l(p)})});return Li(g)};k.qh=function(a,b){return new tA(a,b,20969472,null)};k.Sg=function(){Wy(0)};k.Pg=function(){Wy(1)};k.Uh=function(){Wy(2)};k.Qg=function(){zb("MediaRouter.CastStreaming.Session.End")};
k.Cf=function(a){Ab("MediaRouter.CastStreaming.Start.Failure",a,Ni)};k.Rg=function(){zb("MediaRouter.CastStreaming.Stream.End")};
k.Ei=function(a){var b=this;return this.u?Promise.resolve():(new Promise(function(c){return chrome.metricsPrivate.getIsCrashReportingEnabled(c)})).then(function(c){var d=c&&cz(),e=[9351424];d&&e.push(20969472);return xA(a,e).then(function(f){var g=f[f.length-1];f=qm(f[0].events).catch(function(h){b.O.error("Failed to persist events Blob.",h)});d&&0<g.events.size?Zy(g.events,void 0,b.tt.bind(b)):c&&Yy("stats.json",g.If,void 0,void 0);return f})})};
k.tt=function(a){if(a){a=bz();var b=Date.now();a.g=b}};k.Rj=function(a){if(this.u)return cb();B(this.O,"Received message to upload logs for "+a);return this.g?xA(this.g,[20969472]).then(function(b){b=n(b).next().value;return 0==b.events.size?"":Zy(b.events,a)}):Promise.resolve(FA(this,a))};
var FA=function(a,b){var c=window.localStorage.getItem("mr.temp.mirror.cast.Service.eventsBlob");if(null==c||1>c.length)c=null;else{for(var d=new Uint16Array(c.length),e=0;e<c.length;++e)d[e]=c.charCodeAt(e);c=d.buffer;d=(new Uint8Array(c,c.byteLength-1,1))[0];c=new Uint8Array(c,0,c.byteLength-(0==d?2:1));c=new Blob([c],{type:"application/gzip"})}if(null!=c&&0!=c.size)return qm(new Blob),B(a.O,"Uploading saved logs for feedback."),Zy(c,b)};k=AA.prototype;
k.onError=function(a){this.L&&(this.L(a),this.R=this.L=null,this.Cf(9));B(this.O,"Mirroring service error: "+a);this.o()};k.didStart=function(){this.R&&(this.R(),this.R=this.L=null);this.W&&(this.W.end(),this.W=null);this.Fa=Vy();uj(this.H)?this.Sg():vj(this.H)?this.Pg():sj(this.H)&&this.Uh()};k.didStop=function(){this.o()};k.send=function(a){if(this.m){var b=JSON.parse(a.jsonFormatData);mb(this.O,function(){return"Sending message: "+JSON.stringify(b)});this.m.sendMessage(a.jsonFormatData,{namespace:a.messageNamespace})}};
k.ut=function(a){if(a&&(a.namespace_===mojo.MirroringWebRtcNamespace||a.namespace_===mojo.MirroringRemotingNamespace)&&this.D){var b=new mojo.MirroringCastMessage;b.messageNamespace=a.namespace_;"string"!==typeof a.data?B(this.O,"Received non-string as JSON"):(b.jsonFormatData=a.data,this.D.send(b))}};
var BA=function(a,b){a.J=new mojo.Binding(mojo.MirroringSessionObserver,a,null);a.G=new mojo.Binding(mojo.MirroringCastMessageChannel,a,null);a.m=Px(b.id);a.m.onMessage=a.ut.bind(a)},CA=function(a,b){var c=new mojo.MirroringSessionParameters;c.receiverAddress=new mojo.IPAddress;c.receiverAddress.addressBytes=a.sb.Gf.split(".").map(function(d){return parseInt(d,10)});c.receiverModelName=a.sb.ee;c.type=b.shouldCaptureVideo&&b.shouldCaptureAudio?mojo.MirroringSessionType.AUDIO_AND_VIDEO:b.shouldCaptureVideo?
mojo.MirroringSessionType.VIDEO_ONLY:mojo.MirroringSessionType.AUDIO_ONLY;return c},DA=function(a,b,c,d){a.l=new mojo.MirroringServiceHostPtr;b=b.sb.tabId||-1;uj(c)?a.j.getMirroringServiceHostForTab(b,mojo.makeRequest(a.l)):vj(c)?a.j.getMirroringServiceHostForDesktop(-1,a.da,mojo.makeRequest(a.l)):sj(c)?(b=new mojo.Url,b.url=c,a.j.getMirroringServiceHostForOffscreenTab(b,d||"",mojo.makeRequest(a.l))):a.l=null},EA=function(a,b,c){uj(c)&&!chrome.tabs.onUpdated.hasListener(a.sa)&&chrome.tabs.onUpdated.addListener(a.sa);
(uj(c)||sj(c))&&Cj(a.w,b.sb.tabId)};AA.prototype.xa=function(a,b,c){rj(14);this.w&&Ej(this.w,a,b,c)};
AA.prototype.o=function(){chrome.tabs.onUpdated.removeListener(this.sa);return this.u?this.ja?this.l?(this.l.ptr.reset(),this.D=this.l=null,this.m&&this.m.Xa(),this.m=null,this.J&&(this.J.close(),this.J=null),this.G&&(this.G.close(),this.G=null),Dj(this.j,this.w.h.id),this.w=null,this.da=this.H="",this.Fa&&(this.Fa.end(),this.Fa=null),this.Qg(),Promise.resolve(!0)):Promise.resolve(!1):Promise.reject("Not initialized"):xj.prototype.o.call(this)};
AA.prototype.Rb=function(a,b,c,d,e,f){return this.u?Ki(Error("Mirroring service does not support updating stream")):xj.prototype.Rb.call(this,a,b,c,d,e,f)};AA.prototype.send=AA.prototype.send;AA.prototype.didStop=AA.prototype.didStop;AA.prototype.didStart=AA.prototype.didStart;AA.prototype.onError=AA.prototype.onError;var GA=new AA;oj("mr.mirror.cast.Service",GA);
